### ISSUE TITLE
Mobile see's Firefox 35.0.1 as "Mobile"

### ISSUE THREAD

**Issue by chadsterBAM** [scottsweb/mobble#5]
I am using the below code :

		<div><?php if (!is_mobile()) { the_post_thumbnail('full'); }  else { the_post_thumbnail('banner_mobile'); } ?></div>

And on DESKTOP 2550x1440 I am getting the banner_mobile size.

**Comment by scottsweb** [comment]
In order to debug this you will need to provide your current browser details and also test that your browser is being correctly identified here: http://demo.mobiledetect.net/

You could also try testing the GitHub version of the plugin (https://github.com/scottsweb/mobble/archive/master.zip) as this is using the latest version of the mobile detect PHP library.

Finally you need to ensure your site is not caching pages. mobble is unlikely to work in this scenario (although there are reports of working setups using various hosts/plugins).

**Comment by chadsterBAM** [comment]
Really? I had no idea you couldn't use caching with it... not sure what to do now.  Looks like you're right.  is_mobile shows as false on the demo page.

**Comment by scottsweb** [comment]
There are reports of full page caching working on WPEngine and with W3TC https://wordpress.org/support/topic/w3-total-cache-plugin-conflict-with-mobble-plugin?replies=10 with mobble. 

The only other alternative is to move everything to JavaScript but I have not found a sensible way forward for that yet.
